# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: human_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'human_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15human_detection.proto\x12\x0fhuman_detection\"&\n\x10\x44\x65tectionRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\";\n\x11\x44\x65tectionResponse\x12&\n\x06humans\x18\x01 \x03(\x0b\x32\x16.human_detection.Human\"[\n\x05Human\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x32\n\x0c\x62ounding_box\x18\x03 \x01(\x0b\x32\x1c.human_detection.BoundingBox\"I\n\x0b\x42oundingBox\x12\r\n\x05x_min\x18\x01 \x01(\x02\x12\r\n\x05y_min\x18\x02 \x01(\x02\x12\r\n\x05x_max\x18\x03 \x01(\x02\x12\r\n\x05y_max\x18\x04 \x01(\x02\x32\xbc\x01\n\x0eHumanDetection\x12O\n\x06\x44\x65tect\x12!.human_detection.DetectionRequest\x1a\".human_detection.DetectionResponse\x12Y\n\x0cStreamDetect\x12!.human_detection.DetectionRequest\x1a\".human_detection.DetectionResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'human_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONREQUEST']._serialized_start=42
  _globals['_DETECTIONREQUEST']._serialized_end=80
  _globals['_DETECTIONRESPONSE']._serialized_start=82
  _globals['_DETECTIONRESPONSE']._serialized_end=141
  _globals['_HUMAN']._serialized_start=143
  _globals['_HUMAN']._serialized_end=234
  _globals['_BOUNDINGBOX']._serialized_start=236
  _globals['_BOUNDINGBOX']._serialized_end=309
  _globals['_HUMANDETECTION']._serialized_start=312
  _globals['_HUMANDETECTION']._serialized_end=500
# @@protoc_insertion_point(module_scope)
