# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import human_detection_pb2 as human__detection__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in human_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HumanDetectionStub(object):
    """The HumanDetection service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/human_detection.HumanDetection/Detect',
                request_serializer=human__detection__pb2.DetectionRequest.SerializeToString,
                response_deserializer=human__detection__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.StreamDetect = channel.stream_stream(
                '/human_detection.HumanDetection/StreamDetect',
                request_serializer=human__detection__pb2.DetectionRequest.SerializeToString,
                response_deserializer=human__detection__pb2.DetectionResponse.FromString,
                _registered_method=True)


class HumanDetectionServicer(object):
    """The HumanDetection service definition.
    """

    def Detect(self, request, context):
        """Sends a detection request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDetect(self, request_iterator, context):
        """Sends a stream detection request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HumanDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=human__detection__pb2.DetectionRequest.FromString,
                    response_serializer=human__detection__pb2.DetectionResponse.SerializeToString,
            ),
            'StreamDetect': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDetect,
                    request_deserializer=human__detection__pb2.DetectionRequest.FromString,
                    response_serializer=human__detection__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'human_detection.HumanDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('human_detection.HumanDetection', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HumanDetection(object):
    """The HumanDetection service definition.
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/human_detection.HumanDetection/Detect',
            human__detection__pb2.DetectionRequest.SerializeToString,
            human__detection__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDetect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/human_detection.HumanDetection/StreamDetect',
            human__detection__pb2.DetectionRequest.SerializeToString,
            human__detection__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
